language: php

sudo: false

php:
  - 5.6
  - 7.0

matrix:
  include:
    - php: 5.6
      env: COLLECT_COVERAGE=true
    - php: 7.0
  allow_failures:
    - php: 7.0
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --prefer-dist

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - composer code-style

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - if [ "$COLLECT_COVERAGE" == "true" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
